main: "Rice quietly blocks spam, bad links, and dangerous activityâ€¦!"
prefix: "automod"

commands:
    summary: ""

    add-filter: ""
    remove-filter: ""
    toggle-anti-spam: ""
    toggle-anti-link: ""
    toggle-anti-raid: ""