desc: "Rice quietly blocks spam, bad links, and dangerous activityâ€¦!"
prefix: "automod"

commands:
    summary:
        desc: ""
    add-filter:
        desc: ""
    remove-filter:
        desc: ""
    toggle-anti-spam: 
        desc: ""
    toggle-anti-link: 
        desc: ""
    toggle-anti-raid: 
        desc: ""