desc: "Rice can show helpful info about users, the server, and moreâ€¦!"
prefix: "info"

commands:
    userinfo: 
        desc: ""
    serverinfo: 
        desc: ""
    channelinfo: 
        desc: ""
    roleinfo: 
        desc: ""
    avatar: 
        desc: ""
    banner: 
        desc: ""
    emojis: 
        desc: ""