main: "Rice can show helpful info about users, the server, and moreâ€¦!"
prefix: "info"

commands:
    userinfo: ""
    serverinfo: ""
    channelinfo: ""
    roleinfo: ""
    avatar: ""
    banner: ""
    emojis: ""