main: "Rice helps manage roles, channels, and server settingsâ€¦!"
prefix: "manage"

commands:
    add-role: ""
    remove-role: ""
    info-role: ""

    create-tag: ""
    send-tag: ""

    nickname: ""
    announce: ""
    pin: ""
    poll: ""