main: "Rice will gently help keep the server safe from troubleâ€¦!"
prefix: "mod"

commands:
  kick: ""
  ban: ""
  unban: ""
  timeout: ""
  warn: ""
  warnings: ""
  purge: ""
  lock: ""
  unlock: ""
  slowmode: ""