desc: "Rice will gently help keep the server safe from troubleâ€¦!"
prefix: "mod"

commands:
  kick:
    desc: ""
  ban:
    desc: ""
  unban: 
    desc: ""
  timeout: 
    desc: ""
  warn: 
    desc: ""
  warnings: 
    desc: ""
  purge: 
    desc: ""
  lock: 
    desc: ""
  unlock: 
    desc: ""
  slowmode: 
    desc: ""