desc: "U-um… Rice can help with small tasks and useful tools…!"
prefix: "util"

commands:
    remind: 
        desc: ""
    timer: 
        desc: ""
    translate: 
        desc: ""
    color: 
        desc: ""
    suggest: 
        desc: ""
    report: 
        desc: ""
    quote: 
        desc: ""
    todo: 
        desc: ""
    roll: 
        desc: ""
