desc: "Rice helps manage roles, channels, and server settingsâ€¦!"
prefix: "manage"

commands:
    add-role: 
        desc: ""
    remove-role: 
        desc: ""
    info-role:
        desc: ""

    create-tag: 
        desc: ""
    send-tag: 
        desc: ""

    nickname: 
        desc: ""
    announce: 
        desc: ""
    pin: 
        desc: ""
    poll: 
        desc: ""